name: ci-android

on: [push]

jobs:
  ci-job:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ndk: [r23c, r24]
        os: [ubuntu-latest]
        target: [arm64-v8a, armeabi-v7a, "armeabi-v7a with NEON", x86, x86_64]
        build-type: [Debug, Release]
    steps:
    - uses: actions/checkout@v3
    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: ${{ matrix.ndk }}
        add-to-path: true
    - name: ci-step
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      shell: bash
      run: |
        . ci.sh "-DANDROID_ABI=${{ matrix.target }}|-DCMAKE_TOOLCHAIN_FILE:PATH=${{ steps.setup-ndk.outputs.ndk-path }}/build/cmake/android.toolchain.cmake|-DCMAKE_BUILD_TYPE=${{ matrix.build-type }}"
