name: ci-mingw

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on: [push]

jobs:
  ci-job:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        build-type: [Debug, Release]
    steps:
    - uses: actions/checkout@v4
    - name: Update mingw64
      run: choco upgrade mingw -y --no-progress
    - name: ci-step
      shell: bash
      run: |
        export "PATH=/c/ProgramData/mingw64/mingw64/bin:$PATH" && \
        . ci.sh "-G|MinGW Makefiles|-DCMAKE_BUILD_TYPE=${{ matrix.build-type }}"
