name: ci-old-gcc

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on: [push]

jobs:
  gcc-4:
    runs-on: ubuntu-latest
    container:
      image: library/gcc:4
    steps:
    - name: crutch
      shell: bash
      run: |
        # https://github.com/actions/checkout/issues/1809
        echo "ACTIONS_RUNNER_FORCED_INTERNAL_NODE_VERSION=node16" >> $GITHUB_ENV
        echo "ACTIONS_RUNNER_FORCE_ACTIONS_NODE_VERSION=node16" >> $GITHUB_ENV
        # https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
        echo "ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION=true" >> $GITHUB_ENV
        exit 0
    - uses: actions/checkout@v3
    - name: update-ssl-certs
      shell: bash
      run: ./update-ssl-certs.sh
    - name: ci-step
      shell: bash
      run: ./ci.sh
  gcc-5:
    runs-on: ubuntu-latest
    container:
      image: library/gcc:5
    steps:
    - name: crutch
      shell: bash
      run: |
        # https://github.com/actions/checkout/issues/1809
        echo "ACTIONS_RUNNER_FORCED_INTERNAL_NODE_VERSION=node16" >> $GITHUB_ENV
        echo "ACTIONS_RUNNER_FORCE_ACTIONS_NODE_VERSION=node16" >> $GITHUB_ENV
        # https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
        echo "ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION=true" >> $GITHUB_ENV
        exit 0
    - uses: actions/checkout@v3
    - name: update-ssl-certs
      shell: bash
      run: ./update-ssl-certs.sh
    - name: ci-step
      shell: bash
      run: ./ci.sh
  gcc-6:
    runs-on: ubuntu-latest
    container:
      image: library/gcc:6
    steps:
    - name: crutch
      shell: bash
      run: |
        # https://github.com/actions/checkout/issues/1809
        echo "ACTIONS_RUNNER_FORCED_INTERNAL_NODE_VERSION=node16" >> $GITHUB_ENV
        echo "ACTIONS_RUNNER_FORCE_ACTIONS_NODE_VERSION=node16" >> $GITHUB_ENV
        # https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
        echo "ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION=true" >> $GITHUB_ENV
        exit 0
    - uses: actions/checkout@v3
    - name: update-ssl-certs
      shell: bash
      run: ./update-ssl-certs.sh
    - name: ci-step
      shell: bash
      run: ./ci.sh
  gcc-7:
    runs-on: ubuntu-latest
    container:
      image: library/gcc:7
    steps:
    - uses: actions/checkout@v4
    - name: update-ssl-certs
      shell: bash
      run: ./update-ssl-certs.sh
    - name: ci-step
      shell: bash
      run: ./ci.sh
  gcc-8:
    runs-on: ubuntu-latest
    container:
      image: library/gcc:8
    steps:
    - uses: actions/checkout@v4
    - name: update-ssl-certs
      shell: bash
      run: ./update-ssl-certs.sh
    - name: ci-step
      shell: bash
      run: ./ci.sh
  gcc-9:
    runs-on: ubuntu-latest
    container:
      image: library/gcc:9
    steps:
    - uses: actions/checkout@v4
    - name: update-ssl-certs
      shell: bash
      run: ./update-ssl-certs.sh
    - name: ci-step
      shell: bash
      run: ./ci.sh
