name: ci-posix

on: [push]

jobs:
  ci-job:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, ubuntu-20.04, macos-14, macos-13, macos-12]
        build-type: [Debug, Release]
    steps:
    - uses: actions/checkout@v4
    - name: ci-step
      shell: bash
      run: |
        . ci.sh "-DCMAKE_BUILD_TYPE=${{ matrix.build-type }}"
