name: ci-windows

on: [push]

jobs:
  ci-job:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build-type: [Debug, Release]
        target: [x64, Win32, ARM, ARM64]
        toolset: [v141, v142, v143]
        dll: [ON, OFF]
        without_crt: [ON, OFF]
    steps:
    - uses: actions/checkout@v3
    - name: ci-step
      env:
        CI_MAKE_TARGET: ""
      shell: bash
      run: |
        . ci.sh "-A|${{ matrix.target }}|-T|${{ matrix.toolset }}|-DCMAKE_BUILD_TYPE=${{ matrix.build-type }}|-DMDBX_BUILD_SHARED_LIBRARY:BOOL=${{ matrix.dll }}|-DMDBX_WITHOUT_MSVC_CRT:BOOL=${{ matrix.without_crt }}" \
          "--config|${{ matrix.build-type }}" "--build-config|${{ matrix.build-type }}"
