name: ci-windows

on: [push]

jobs:
  ci-job:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, windows-2019]
        build-type: [Debug, Release]
        target: [x64, Win32, ARM, ARM64]
    steps:
    - uses: actions/checkout@v2
    - name: ci-step
      shell: bash
      run: |
        ./ci.sh "-A|${{ matrix.target }}|-DCMAKE_BUILD_TYPE=${{ matrix.build-type }}" \
           "--config|${{ matrix.build-type }}" "--build-config|${{ matrix.build-type }}"
