name: ci-windows

on: [push]

jobs:
  ci-job:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, windows-2019]
        build-type: [Debug, Release]
        target: [x64, Win32, ARM, ARM64]
        toolset: [v141, v142, v143]
        exclude:
          - os: windows-latest
            toolset: v141
          - os: windows-2019
            toolset: v143
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: ci-step
      shell: bash
      run: |
        . ci.sh "-A|${{ matrix.target }}|-T|${{ matrix.toolset }}|-DCMAKE_BUILD_TYPE=${{ matrix.build-type }}" \
           "--config|${{ matrix.build-type }}" "--build-config|${{ matrix.build-type }}"
